import typescript from '@rollup/plugin-typescript';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import { terser } from 'rollup-plugin-terser';
import json from '@rollup/plugin-json';

// GAS用のバナー
const banner = `// Google Apps Script Bundle - Auto-generated
// Do not edit this file manually`;

export default [
  {
    input: 'gas_src/analyzer.ts',
    output: {
      file: 'gas/Analyzer.gs',
      format: 'iife',
      name: 'AnalyzerBundle',
      banner: banner,
      globals: {
        'mathjs': 'math',
        'zod': 'z'
      }
    },
    external: ['mathjs', 'zod'], // 外部ライブラリはCDNから読み込む
    plugins: [
      resolve({
        browser: true,
        preferBuiltins: false
      }),
      commonjs(),
      typescript({
        tsconfig: './gas_src/tsconfig.json',
        declaration: false,
        declarationMap: false
      }),
      json(),
      terser({
        format: {
          comments: false,
          preamble: banner
        }
      })
    ]
  },
  {
    input: 'gas_src/estate.ts',
    output: {
      file: 'gas/Estate.gs',
      format: 'iife',
      name: 'EstateBundle',
      banner: banner,
      globals: {
        'zod': 'z'
      }
    },
    external: ['zod'], // zodはCDNから読み込む
    plugins: [
      resolve({
        browser: true,
        preferBuiltins: false
      }),
      commonjs(),
      typescript({
        tsconfig: './gas_src/tsconfig.json',
        declaration: false,
        declarationMap: false
      }),
      json(),
      terser({
        format: {
          comments: false,
          preamble: banner
        }
      })
    ]
  }
];
